Create a separate requirements file for the CI
XanaduAI/strawberryfields pull request #629
Opened 2021-09-23 17:37 UTC by sduquemesa

**Context:** The requirements.txt file has packages unpinned. This is contrary to the convention of pinning packages in the requirements.txt file.

**Description of the Change:** Create a separate `requirements.txt` (pinned) and `requirements-ci.txt` (unpinned). This latter is used by the CI.

**Benefits:** CI environment will behave closely as when installing the package with `setup.py`

**Possible Drawbacks:** Version conflicts on (unpinned) dependencies potentially will only appear on CI environment.

**Related GitHub Issues:** #582

2021-09-23 20:25 UTC, thisac requested changes
Thanks @sduquemesa. I'd think we should strictly pin all dependencies in the `requirements.txt` file to latest releases (e.g. `numpy==1.21` instead of `numpy>=1.19.2`), unless already pinned (then keeping them is probably good).

I'm not sure about best practice when it comes to completely unpinning `requirements-ci.txt` (i.e. not even having a minimum version). This seems to be the case in PL, though.

2021-09-23 20:25 UTC, thisac commented on requirements-ci.txt
> +git+https://github.com/XanaduAI/blackbird@master#egg=quantum-blackbird
We should be able to use the released version of Blackbird now.
```suggestion
quantum-blackbird
```

2021-09-23 20:25 UTC, thisac commented on requirements.txt
>  git+https://github.com/XanaduAI/blackbird@master#egg=quantum-blackbird
Same here!
```suggestion
quantum-blackbird==0.4.0
```

2021-09-24 16:38 UTC, sduquemesa commented
@thisac, following the discussion on issues #582, this is the reply from @antalszava:

> Yes! The idea would be to only pin only those packages to a certain version in the requirements-ci.txt file where there is a specific constraint (i.e., SF only works with a certain version of the dependency). The rest of the packages would stay unpinned so that when issuing pip install -r requirements-ci.txt, the latest version for each package is installed by the continuous integration check.

In contrast, in the requirements.txt file we would like to provide the user with a working setup to use Strawberry Fields. We provide a list of dependencies with pinned versions, such that by doing pip install -r requirements.txt, they will get a working combination of dependencies and be able to use Strawberry Fields.

2021-09-24 17:12 UTC, thisac commented
Thanks @sduquemesa! We should update the recently merged `.github/workflows/upload.yml` file to use `pip install -r requirements-ci.txt` as well, so that we're testing with the same package versions for release. Looks good otherwise! 💯

2021-09-30 20:49 UTC, thisac approved these changes
Thanks for pinging me on this @sduquemesa!

2021-09-30 20:49 UTC, thisac commented on requirements.txt
> +numba
How come `numba` isn't pinned anymore?

2021-09-30 20:49 UTC, thisac commented on .github/workflows/upload.yml
> +          pip install -r requirements-ci.txt
🎉

2021-10-04 14:55 UTC, sduquemesa commented on requirements.txt
> +numba
Sorry, my bad 😖 Fixed now!

2021-10-04 15:20 UTC, merged